# Version of the configuration file
version: 4.0.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: 
    light: /img/logo.svg
    dark: /img/logo-dark.svg
# Page metadata configurations
head:
  # URL or path to the website's icon
  favicon: /img/favicon.svg
  # Web application manifests configuration
  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  manifest:
    # Name of the web application (default to the site title)
    name: "Thien Nguyen's Blog"
    # The displayed name of the web application
    # when there is not enough space to display full name
    short_name: "Thien Nguyen's Blog"
    # The start URL of the web application
    start_url:
    # The default theme color for the application
    theme_color: "#3273dc"
    # A placeholder background color for the application page to display
    # before its stylesheet is loaded
    background_color: "#3273dc"
    # The preferred display mode for the website
    display: standalone
    # Image files that can serve as application icons for different contexts
    icons:
    - # The path to the image file
      src: "/img/favicon.svg"
      # A string containing space-separated image dimensions
      sizes: "24x24 32x32 64x64 128x128"
      # A hint as to the media type of the image
      type: "image/svg+xml"
  # Open Graph metadata
  # https://hexo.io/docs/helpers.html#open-graph
  open_graph:
    # Page title (og:title) (optional)
    # You should leave this blank for most of the time
    title:
    # Page type (og:type) (optional)
    # You should leave this blank for most of the time
    type: blog
    # Page URL (og:url) (optional)
    # You should leave this blank for most of the time
    url:
    # Page cover (og:image) (optional)
    # You should leave this blank for most of the time
    image:
    # Site name (og:site_name) (optional)
    # You should leave this blank for most of the time
    site_name:
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author:
    # Page description (og:description) (optional)
    # You should leave this blank for most of the time
    description:
    # Twitter card type (twitter:card)
    twitter_card:
    # Twitter ID (twitter:creator)
    twitter_id:
    # Twitter Site (twitter:site)
    twitter_site:
    # Google+ profile link (deprecated)
    google_plus:
    # Facebook admin ID
    fb_admins:
    # Facebook App ID
    fb_app_id:
  # Structured data of the page
  # https://developers.google.com/search/docs/guides/intro-structured-data
  structured_data:
    # Page title (optional)
    # You should leave this blank for most of the time
    title:
    # Page description (optional)
    # You should leave this blank for most of the time
    description:
    # Page URL (optional)
    # You should leave this blank for most of the time
    url:
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author:
    # Page publisher (optional)
    # You should leave this blank for most of the time
    publisher:
    # Page publisher logo (optional)
    # You should leave this blank for most of the time
    publisher_logo:
    # Page images (optional)
    # You should leave this blank for most of the time
    image:
  # Additional HTML meta tags in an array
  meta:
  # Meta tag specified in <attribute>=<value> style
  # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
    - 'name=theme-color;content=#123456'
    - 'name=generator;content=Hexo 4.2.0'
    - 'name=description;content=Author: Thien Nguyen, Category: Blogs, Technology, Developer'
  # URL or path to the website's RSS atom.xml
  rss:
# Page top navigation bar configurations
navbar:
  # Navigation menu items
  menu:
    Home: 
      path: /
    Archives: 
      path: /archives
    Categories:
      path: /categories
    # Thẻ: /tags
    # Misc:
    #   path: /misc
    #   children:
    #     Music:
    #       path: /categories/music
    #       # icon: fab fa-github
    #     Note:
    #       path: /note
    Relax:
      path: /categories/music
    CV: 
      path: /cv
    About: 
      path: /about
    Contact: 
      path: /contact
  langauge_menu_selected: 1 # index of selected menu lanauage 
  language_menu_title: "Select site language"
  language_menu: 
    - # Vietnamese
      name: "Tiếng Việt"
      path: "https://vi.thiennguyen.dev"
      flag: "https://thiennguyen.dev/assets/img/vi-vn-64x64.png"
    - # English
      name: "English"
      path: "https://thiennguyen.dev"
      flag: "https://thiennguyen.dev/assets/img/en-us-64x64.png"
  # Links to be shown on the right of the navigation bar
  links:
    View Profile on Facebook:
      icon: fab fa-facebook
      url: https://www.facebook.com/thiennguyen.dev/
    View Profile on LinkedIn:
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/thiennguyendev/
    View Profile on GitHub:
      icon: fab fa-github
      url: "https://github.com/thiennguyen93"
# Page footer configurations
footer:
  # Links to be shown on the right of the footer section
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
    View Profile on GitHub:
      icon: fab fa-github
      url: "https://github.com/thiennguyen93"
# Article related configurations
article:
  # Code highlight settings
  highlight:
    # Code highlight themes
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-light
    # Show copy code button
    clipboard: true
    # Default folding status of the code blocks. Can be "", "folded", "unfolded"
    fold: unfolded
  # Whether to show estimated article reading time
  readtime: false
  # Whether to show updated time. For "auto", shows article update time only when page.updated is set and it is different from page.date
  update_time: true
  # Article licensing block
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: "https://creativecommons.org/licenses/by-nc/4.0/"
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
  type: insight
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
  type: facebook
  # Disqus shortname
  shortname: ""
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
# "Buy me a coffee" donate button configurations
- type: buymeacoffee
  # URL to the "Buy me a coffee" page
  url: "https://www.buymeacoffee.com/thiennguyen"
# Patreon donate button configurations
- type: patreon
  # URL to the Patreon page
  url: "https://www.patreon.com/thiennguyen"
# Paypal donate button configurations
- type: paypal
  # Paypal business ID or email address
  business: "tuctrungsoft@gmail.com"
  # Currency code
  currency_code: USD
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share: null
#     type: sharethis
#     # URL to the ShareThis share plugin script          //addthis.com phuocthien@outlook.com
#     install_url: '//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-61108dd8f8025362'
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
  # Left sidebar configurations
  left:
    # Whether the sidebar sticks to the top when page scrolls
    sticky: true
  # Right sidebar configurations
  right:
    # Whether the sidebar sticks to the top when page scrolls
    sticky: true
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
# Profile widget configurations
- # Where should the widget be placed, left sidebar or right sidebar
  position: left
  type: profile
  # Author name
  author: Thiện Nguyễn
  # Author title
  author_title: Software Engineer
  # Author's current location
  location: Ho Chi Minh City, Vietnam
  # URL or path to the avatar image
  avatar:
  # Whether show the rounded avatar image
  avatar_rounded: true
  # Email address for the Gravatar
  gravatar: phuocthien@outlook.com
  # URL or path for the follow button
  follow_link: "https://thiennguyen.dev/cv"
  follow_title: "View resume"
  # Links to be shown on the bottom of the profile widget
  social_links:
      Github:
        icon: fab fa-github
        url: "https://thiennguyen93.github.io/"
        tooltip: "View my Github Page"
        classNames: [has-tooltip-arrow, has-tooltip-bottom]
      LinkedIn:
        icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/thiennguyendev/"
        tooltip: "Go to my profile on Linkedin"
        classNames: [has-tooltip-arrow, has-tooltip-bottom]
      Contact:
        icon: fas fa-at
        url: "/contact"
        tooltip: "Contact me"
        target:  "_self"
        classNames: [has-tooltip-arrow, has-tooltip-bottom]
# Table of contents widget configurations
- # Where should the widget be placed, left sidebar or right sidebar
  position: left
  type: toc
  # Whether to show the index of each heading
  index: true
  # Whether to collapse sub-headings when they are out-of-view
  collapsed: true
  # Maximum level of headings to show (1-6)
  depth: 3

# # Recommendation links widget configurations
# -
#     # Where should the widget be placed, left sidebar or right sidebar
#     position: left
#     type: links
#     # Names and URLs of the sites
#     links:
#         Hexo: 'https://hexo.io'
#         Bulma: 'https://bulma.io'

# Categories widget configurations
- # Where should the widget be placed, left sidebar or right sidebar
  position: left
  type: categories
# Recent posts widget configurations
- # Where should the widget be placed, left sidebar or right sidebar
  position: left
  type: recent_posts
# Archives widget configurations
- # Where should the widget be placed, left sidebar or right sidebar
  position: left
  type: archives
# Tags widget configurations
- # Where should the widget be placed, left sidebar or right sidebar
  position: left
  type: tags
  # # Google FeedBurner email subscription widget configurations
  # -
  #     # Where should the widget be placed, left sidebar or right sidebar
  #     position: left
  #     type: subscribe_email
  #     # Hint text under the email input
  #     description:
  #     # Feedburner ID
  #     feedburner_id: ''
  # Google AdSense unit configurations
  # -
  # Where should the widget be placed, left sidebar or right sidebar
  # position: left
  # type: adsense
  # # AdSense client ID
  # client_id: ''
  # # AdSense AD unit ID
  # slot_id: ''
  # # Follow.it email subscription widget configurations
  # -
  #     # Where should the widget be placed, left sidebar or right sidebar
  #     position: left
  #     type: followit
  #     # Hint text under the email input
  #     description:
  #     # Subscription form action URL
  #     action_url: ''
  #     # Feed claiming verification code
  #     verification_code: ''
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
  # Enable page startup animations
  animejs: true
  # Show the "back to top" button
  back_to_top: true
  # Baidu Analytics plugin settings
  # https://tongji.baidu.com
  baidu_analytics: false
  # Bing Webmaster Tools plugin settings
  # https://www.bing.com/toolbox/webmaster/
  bing_webmaster: false
  # BuSuanZi site/page view counter
  # https://busuanzi.ibruce.info
  busuanzi: false
  # CNZZ statistics
  # https://www.umeng.com/web
  cnzz: false
  # Alerting users about the use of cookies
  # https://www.osano.com/cookieconsent/
  cookie_consent:
    # The compliance type. Can be "info", "opt-in", or "opt-out"
    type: info
    # Theme of the popup. Can be "block", "edgeless", or "classic"
    theme: edgeless
    # Whether the popup should stay static regardless of the page scrolls
    static: false
    # Where on the screen the consent popup should display
    position: bottom-left
    # URL to your site's cookie policy
    policyLink: "https://www.cookiesandyou.com/"
  # Enable the lightGallery and Justified Gallery plugins
  gallery: true
  # Google Analytics plugin settings
  # https://analytics.google.com
  google_analytics: false
  # Google Analytics tracking ID
  # tracking_id:
  # Hotjar user feedback plugin
  # https://www.hotjar.com/
  hotjar: false
  # Hotjar site id
  # site_id:
  # Enable the KaTeX math typesetting support
  # https://katex.org/
  katex: false
  # Enable the MathJax math typesetting support
  # https://www.mathjax.org/
  mathjax: false
  # Enable the Outdated Browser plugin
  # http://outdatedbrowser.com/
  outdated_browser: false
  # Show a progress bar at top of the page on page loading
  progressbar: true
  # Statcounter statistics
  # https://statcounter.com/
  statcounter: false
    # Statcounter project id
    ## project: 12577343 <<<--uncomment this to use
    # Statcounter project security code
    ## security: 027ff2d5 <<--uncomment this to use
  # Twitter conversion tracking plugin settings
  # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
  twitter_conversion_tracking:
    # Twitter Pixel ID
    pixel_id:
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  # Name or URL template of the JavaScript and/or stylesheet CDN provider
  cdn: unpkg
  # Name or URL template of the webfont CDN provider
  fontcdn: google
  # Name or URL of the fontawesome icon font CDN provider
  iconcdn: fontawesome