name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo "artifactname=${GH_TOKEN}" >> $GITHUB_ENV
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "github-actions"
        git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "git@github.com:"
        npm run myinstall
        npm run build-gh-page
