name: Deploy website thiennguyen.dev

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
          GH_TOKEN_ICARUS_CUSTOM_THEME: ${{ secrets.GH_TOKEN_ICARUS_CUSTOM_THEME }}
          GH_PRIVATE_THEME_REPOSITORY: ${{ secrets.GH_PRIVATE_THEME_REPOSITORY }}
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "github-actions"
        git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
        npm install
        npm install git+https://${GH_TOKEN_ICARUS_CUSTOM_THEME}@github.com/thiennguyen93/${GH_PRIVATE_THEME_REPOSITORY} --no-save
        npm run build-gh-page
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        enable_jekyll: false
